apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: phonebook-app
  labels:
    app: backend-app
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend-app
          image: gulnarmammadli/backend-final:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://ec2-52-44-209-165.compute-1.amazonaws.com:5432/deofv7um83j18a
            - name: DB_USER
              value: jmtjfnkikjjuhj
            - name: DB_PASSWORD
              value: 43b379745825b01f8b2ad8b63abe4de25240320b08974ccc0006bcf0c0c2f6e2
          volumeMounts:
            - name: back-app-config
              mountPath: /app/config
      volumes:
        - name: back-app-config
          configMap:
            name: back-app-config
