kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: phonebook-app
spec:
  selector:
    app: backend-app
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080